HTTP_STATUS = {
    100: {"name": "Continue", "meaning": "服务器已收到请求头，客户端应继续发送请求主体"},
    101: {"name": "Switching Protocols", "meaning": "服务器正在切换协议"},
    102: {"name": "Processing", "meaning": "服务器已收到并正在处理请求"},
    103: {"name": "Early Hints", "meaning": "在最终响应前返回响应头，让浏览器预加载资源"},

    200: {"name": "OK", "meaning": "请求成功，服务器返回了请求的数据"},
    201: {"name": "Created", "meaning": "请求成功且服务器创建了新资源"},
    202: {"name": "Accepted", "meaning": "请求已接受但尚未处理"},
    203: {"name": "Non-Authoritative Information", "meaning": "服务器成功处理请求，但返回的信息来自其他来源"},
    204: {"name": "No Content", "meaning": "请求成功，但响应体为空"},
    205: {"name": "Reset Content", "meaning": "通知客户端重置文档视图"},
    206: {"name": "Partial Content", "meaning": "服务器返回了资源的部分内容"},
    207: {"name": "Multi-Status", "meaning": "返回多个独立操作的响应状态"},
    208: {"name": "Already Reported", "meaning": "避免重复列出内部成员的绑定"},
    226: {"name": "IM Used", "meaning": "服务器已完成 GET 请求，响应表示实例操作结果"},

    300: {"name": "Multiple Choices", "meaning": "请求的资源有多个可选响应"},
    301: {"name": "Moved Permanently", "meaning": "资源已被永久移动到新 URL"},
    302: {"name": "Found", "meaning": "资源临时位于其他 URL"},
    303: {"name": "See Other", "meaning": "重定向到另一个 URL"},
    304: {"name": "Not Modified", "meaning": "资源未修改，可使用缓存版本"},
    305: {"name": "Use Proxy", "meaning": "（已废弃）要求通过代理访问资源"},
    307: {"name": "Temporary Redirect", "meaning": "临时重定向，保持请求方法不变"},
    308: {"name": "Permanent Redirect", "meaning": "永久重定向，保持请求方法不变"},

    400: {"name": "Bad Request", "meaning": "请求语法错误或参数无效"},
    401: {"name": "Unauthorized", "meaning": "请求需要身份认证"},
    402: {"name": "Payment Required", "meaning": "（保留）未来可能用于数字支付"},
    403: {"name": "Forbidden", "meaning": "服务器理解请求但拒绝执行"},
    404: {"name": "Not Found", "meaning": "服务器找不到请求的资源"},
    405: {"name": "Method Not Allowed", "meaning": "请求方法不被允许"},
    406: {"name": "Not Acceptable", "meaning": "服务器无法生成客户端要求的响应内容"},
    407: {"name": "Proxy Authentication Required", "meaning": "需要先通过代理认证"},
    408: {"name": "Request Timeout", "meaning": "客户端请求超时"},
    409: {"name": "Conflict", "meaning": "请求与服务器当前状态冲突"},
    410: {"name": "Gone", "meaning": "资源已被永久删除"},
    411: {"name": "Length Required", "meaning": "请求头缺少 Content-Length 字段"},
    412: {"name": "Precondition Failed", "meaning": "请求头中的前置条件未满足"},
    413: {"name": "Payload Too Large", "meaning": "请求实体过大"},
    414: {"name": "URI Too Long", "meaning": "请求的 URL 过长"},
    415: {"name": "Unsupported Media Type", "meaning": "请求的媒体格式不被支持"},
    416: {"name": "Range Not Satisfiable", "meaning": "请求的 Range 范围不合法"},
    417: {"name": "Expectation Failed", "meaning": "服务器无法满足 Expect 头部的期望"},
    418: {"name": "I'm a teapot", "meaning": "（愚人节玩笑）服务器是一个茶壶"},
    421: {"name": "Misdirected Request", "meaning": "请求被发送到无法生成响应的服务器"},
    422: {"name": "Unprocessable Entity", "meaning": "请求格式正确但语义错误"},
    423: {"name": "Locked", "meaning": "资源被锁定"},
    424: {"name": "Failed Dependency", "meaning": "请求失败是因为之前的请求失败"},
    425: {"name": "Too Early", "meaning": "服务器拒绝处理可能被重放的请求"},
    426: {"name": "Upgrade Required", "meaning": "客户端应切换到其他协议"},
    428: {"name": "Precondition Required", "meaning": "服务器要求请求带前置条件"},
    429: {"name": "Too Many Requests", "meaning": "客户端发送了过多请求（限流）"},
    431: {"name": "Request Header Fields Too Large", "meaning": "请求头过大"},
    451: {"name": "Unavailable For Legal Reasons", "meaning": "因法律原因导致资源不可访问"},

    500: {"name": "Internal Server Error", "meaning": "服务器内部错误"},
    501: {"name": "Not Implemented", "meaning": "服务器不支持此请求方法"},
    502: {"name": "Bad Gateway", "meaning": "网关或代理收到无效响应"},
    503: {"name": "Service Unavailable", "meaning": "服务器暂时过载或维护中"},
    504: {"name": "Gateway Timeout", "meaning": "网关或代理等待上游服务器超时"},
    505: {"name": "HTTP Version Not Supported", "meaning": "服务器不支持请求的 HTTP 版本"},
    506: {"name": "Variant Also Negotiates", "meaning": "服务器配置错误，导致内容协商死循环"},
    507: {"name": "Insufficient Storage", "meaning": "服务器存储空间不足"},
    508: {"name": "Loop Detected", "meaning": "服务器检测到无限循环"},
    510: {"name": "Not Extended", "meaning": "请求需要进一步扩展才能完成"},
    511: {"name": "Network Authentication Required", "meaning": "需要网络认证"},
}
